travis:
  secure:
    BINSTAR_TOKEN: B6QdINs6NQgzNFlOsgU9zT4eSM2w4OfrKxZ7AfxahVm70q/R8RGlmWrqNDgFqjZIc3CEtNHO+pNyXEMfLAGrDdbEfR8jYqAEaPzC8oK4RZs7BwnHHJb4Kf6i0w0Q2LxUctV/z9RwAwg0g5xxfxe43h2d2ndLubrjkg01+mZ3iosDYPOyHCMJoYq4JJW8BINmarHXT8k9lTjBl6zjhi3OTpV+TL/OKT6LcHsbNexzupt/iv6jnZMf6x8dDCHSZJNONLXC/yAy4l5FuOMikwGzwhvIxXWeY8IT8oJWg9s9ZMlEHWjP4cncakIcVoMPqE9zoJC5HUbJuG1YDlUijtgyDaG97C+VMFEx5ly62RWXbk33XtK+rWTed2x/46tnQtlUlMGCDNUyz4KyXC098JSXkk4LcaVzJizyvhs28NRxUjlLX7Np7Xcs31vQFsDtf9Xdi4Se6HJayieeFXThQLLN98hidug6A68luKfAz3qRBoRQVbtUngypxvI8Zj8lO7Zf6STBRzWkC3kfvt4mODhXDZDwy6BMeEWAlMIhLOy7shojLF3J7ivmVa8BB1yldFmMsqKuyNBIyJYaEay7hKhChPYJzJPoy5LqP2APTJ9YHu0fcskgkzyQYjzlJYa7CTNFylhBPRpOTDuM+5HpqqaK78dnKL/bJm8iYjax6lRnnuo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
